;(setq default-major-mode 'c++-mode)

; odpowiedni tryb dla plików z rozszerzeniami
(setq auto-mode-alist
      (append auto-mode-alist
	      '(
		("\\.txt$"             . text-mode)
		("\\.c$"               . c-mode)
		("\\.C$"               . c++-mode)
		("\\.cc$"              . c++-mode)
		("\\.cpp$"             . c++-mode)
		("\\.cxx$"             . c++-mode)
		("\\.cs$"              . csharp-mode)
		("\\.h$"               . c++-mode)
		("\\.hh$"              . c++-mode)
		("\\.hpp$"             . c++-mode)
		("\\.hxx$"             . c++-mode)
		("\\.d[i]?"            . d-mode)
		("\\.cg$"              . cg-mode)
		("\\.tex$"             . LaTeX-mode)
		("\\.java$"            . java-mode)
		("\\.asm$"             . asm86-mode)
		("\\.inc$"             . asm86-mode)
		("\\.s$"               . gas-mode)
		("\\.S$"               . gas-mode)
;		("\\.sp$"              . spice-mode)
;		("\\.cir$"             . spice-mode)
;		("\\.ckt$"             . spice-mode)
;		("\\.mod$"             . spice-mode)
;		("\\.cdl$"             . spice-mode)
;		("\\.chi$"             . spice-mode)
;		("\\.inp$"             . spice-mode)
		("\\.sh$"              . shell-script-mode)
		("\\rc$"               . shell-script-mode)
		("makefile"            . makefile-mode)
		("Makefile"            . makefile-mode)
		("\\.am$"              . makefile-mode)
		("\\.mk$"              . makefile-mode)
		("\\.mak$"             . makefile-mode)
		("\\.make$"            . makefile-mode)
		("\\.php$"             . php-mode)
		("\\.css$"             . css-mode)
		("\\.v$"               . verilog-mode)
		("\\.va$"              . verilog-mode)
		("\\.vams$"            . verilog-mode)
		("\\.sv$"              . verilog-mode)
		("\\.svh$"             . verilog-mode)
		("\\.il\\'"            . skill-mode)
		("\\.ocn\\'"           . skill-mode)
		("\\.cdf\\'"           . skill-mode)
		("\\.res\\'"           . skill-mode)
		("CMakeLists\\.txt\\'" . cmake-mode)
		("\\.cmake\\'" . cmake-mode)
	       ) auto-mode-alist))
